### ISSUE TITLE
EffectModule 没有经过视图层调用，withLatestFrom(EffectModule ) 不会发出值

### ISSUE THREAD

**Issue by liaoyinglong** [sigi-framework/sigi#116]
https://codesandbox.io/s/sigi-dynamic-import-r8v7i

---
如上代码。

复现步骤：
1. 点击fetchlist button ，loading不会结束

2. 先点击 setLogin(true) button， 在点击 fetchlist button ，loading马上预期结束

预期：
直接点击 fetchlist button 需要，延时后渲染数据

**Comment by Brooooooklyn** [comment]
First, inject module into service is a bad idea, a service was expected to be pure.

I guess you want `fetchList` without dispatch action in `Component` ?

**We absolutely do not recommend to manage side effect in this way**.
We are trying make every side effect as clear as possible in `Sigi` application, and let a side effect happen silently without declare the trigger in `Component` is an anti-pattern using `Sigi`.

**Comment by liaoyinglong** [comment]
感谢你的回答。

你说到的`anti-pattern`给了我一些提示。
