### ISSUE TITLE
依赖注入不生效

### ISSUE THREAD

**Issue by FailLone** [sigi-framework/sigi#228]
在基于create-react-app构建的项目中（基于babel），使用依赖注入不生效

**Comment by Brooooooklyn** [comment]
https://github.com/LeetCode-OpenSource/ayanami/issues/116#issuecomment-576099057

**Comment by FailLone** [comment]
谢谢您！

**Comment by gitHber** [comment]
> 谢谢您！

为啥我添加babel-plugin-transform-typescript-metadata还是不管用呢
