### ISSUE TITLE
What's best practices of dispatching action of injected module when changing router?

### ISSUE THREAD

**Issue by FailLone** [sigi-framework/sigi#236]
I just want to change the status of the target page while changing the route, like:
```js
return payload$.pipe(
          switchMap((payload) => {
            return of(
                this.router.push('/otherRouter'),
                this.injectedModule.getActions().doSomething(payload.id)
            )
          }),
      )
```

But it could report a error `(TypeError: Cannot read property 'dispatch' of null),` maybe because injected module is  never ever been used by a component.

So, could you tell me what should I do in this case?

**Comment by Brooooooklyn** [comment]
Put your `doSomething(payload.id)` in `useEffect` in the `Component` under your target router.
It's make no sense to dispatch actions to a non-initialized module.
@forehalo What do you think about this scenario?

**Comment by FailLone** [comment]
Maybe I should deliver payload in query.

BTW, why does this code cause a dead loop that causes the browser to crash.

```js
switchMap((payload) => {
  return of(this.router.push('/otherRouter'))
          .pipe(
               endWith(this.injectedModule.getActions().doSomething(payload.id), asap),
           )
})
```

**Comment by forehalo** [comment]
thanks for you report.
I did catch an error but it's raised by dispatching a noop action, no dead loop found.
Could you please provide  a simple reproduce method, that can help a lot.

**Comment by forehalo** [comment]
> Maybe I should deliver payload in query.
> 
> BTW, why does this code cause a dead loop that causes the browser to crash.
> 
> ```js
> switchMap((payload) => {
>   return of(this.router.push('/otherRouter'))
>           .pipe(
>                endWith(this.injectedModule.getActions().doSomething(payload.id), asap),
>            )
> })
> ```

**Comment by FailLone** [comment]
> > Maybe I should deliver payload in query.
> > BTW, why does this code cause a dead loop that causes the browser to crash.
> > ```js
> > switchMap((payload) => {
> >   return of(this.router.push('/otherRouter'))
> >           .pipe(
> >                endWith(this.injectedModule.getActions().doSomething(payload.id), asap),
> >            )
> > })
> > ```
> 
> thanks for you report.
> I did catch an error but it's raised by dispatching a noop action, no dead loop found.
> Could you please provide a simple reproduce method, that can help a lot.

That's my bug actually

**Comment by FailLone** [comment]
> Put your `doSomething(payload.id)` in `useEffect` in the `Component` under your target router.
> It's make no sense to dispatch actions to a non-initialized module.
> @forehalo What do you think about this scenario?

Any news? It's really inconvenient passing information through search of URL

**Comment by Brooooooklyn** [comment]
@FailLone I still feel it's a bad idea that dispatch action to a non-initialized module. Think about this scenario: you dispatch `this.injectedModule.getActions().doSomething(payload.id)`, but `injectedModule` doesn't have been `subscribe` yet, and when you `subscribe` it via `useModuleState`, you will miss this action.

I suggest you put the `payload.id` in the state of current module, and get it back from the `injectedModule`

**Comment by FailLone** [comment]
Thank you for your advice！
Is it feasible that if dispatching a action of module haven't been subscribed, modifying it's default state.

**Comment by forehalo** [comment]
@FailLone 
Internally, sigi will only ready the `defaultState` the first time you initialize your module by `useModule` or other hooks. According to that, you can fearlessly change the `defaultState` basically before module initialized.

BTW, I think the same as @Brooooooklyn do. I don't know where you get `payload.id` from, but it's kinda a state from your component or state from another module. That would be confusing if you set **picked** data to `defaultState` at runtime, and of course, I'm not sure the core of sigi won't change somedays, by which your app will be affected.

Till now, we've experienced lots of complicated scenarios that ever challenged sigi's core thinking. they all failed. Sigi is a place to **manage** your side effects. where the effects triggered is still your components and users' actions, so does where your payload **originally** come from** IMO

**Comment by FailLone** [comment]
Yes, you are right. I haven't been able to change my traditional thinking. 
Actually, if ``Module A`` can effect ``Module B`` ever been uninitialized, that means ``Module A`` is the dependency of ``Module B``. 
Maybe they are different or opposite, but they convey the same meaning.
Thanks again! You can close this issue if you need.
