### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by FailLone** [sigi-framework/sigi#237]
When using a selector, if the selector is not declared as a variable, there may be a memory leak (warning by react).
like using:
```js
  const dataSource = useEffectState(Module, {
    selector: state => state.data,
  })
```
instead of
```js
const selector = state => state.data
const dataSource = useEffectState(Module, {
    selector,
  })
```
I don't think it's a bug, but why this happening? I noticed that subscription has been unsubscribed when selector changing.

**Comment by Brooooooklyn** [comment]
No warning in https://codesandbox.io/s/sigi-recipes-state-selector-m4m18?file=/src/index.tsx, how to reproduce?

**Comment by Brooooooklyn** [comment]
> I noticed that subscription has been unsubscribed when selector changing

Yes, this is a by design behavior.
