### ISSUE TITLE
[feature request]   类似react-redux useSelector 第二个参数的eqFn

### ISSUE THREAD

**Issue by liaoyinglong** [sigi-framework/sigi#475]
给`useModule` `useModuleState` 添加一个参数 `equalityFn`减少组件`render`。

[react-redux useSelector](https://react-redux.js.org/api/hooks#equality-comparisons-and-updates)

**Comment by forehalo** [comment]
We've added a required options `dependencies` to hooks with the same aim. React will shallow equal it for us.
```
const addon = 1

useModule(Module, {
  selector: (state) => state.count + addon,
  dependencies: [addon]
})
```

**Comment by liaoyinglong** [comment]
https://codesandbox.io/s/sigi-recipes-state-selector-forked-glypi

 点击 按钮


Foo 组件预期不要更新。

在`react redux`里面可以传递第二个参数来进行自定义比较，判断组件是否更新
