### ISSUE TITLE
devtool bug:  createNoopAction

### ISSUE THREAD

**Issue by yoyooyooo** [sigi-framework/sigi#89]
[index.ts#L38](https://github.com/sigi-framework/sigi/blob/develop/packages/devtool/src/index.ts#L38)

createNoopAction' returned action's type is Symbol.

`!(action.type as string)?.endsWith(INIT_ACTION_TYPE)` should become `!(action.type as string)?.endsWith.?(INIT_ACTION_TYPE)`

**Comment by Brooooooklyn** [comment]
good catch, could you please send a pr to fix this problem?
